### ISSUE TITLE
test should include sample using find

### ISSUE THREAD

**Issue by appsird** [brynbellomy/SwiftDataStructures#1]
It does not appear your XC tests include and example and/or testing the find method. Would appreciate if you could include an example.

**Comment by appsird** [comment]
This applies to the  LinkedList class.

Please also include a test using the at() method.

**Comment by brynbellomy** [comment]
Good catch!  Thanks for taking the time to spot those.  I'll push a change shortly.

**Comment by brynbellomy** [comment]
This has been resolved by e6d52f44c454fd285f3d168f06b2c032348fb96b ... marking this closed.
